### ISSUE TITLE
Too many spool messages

### ISSUE THREAD

**Issue by abamara** [IBM/node-red-contrib-db2-for-i#3]
Hello, 

This part of code cause us some issues :

`console.log("Already connected to DB2 for i with this connection");`

It generate many spool pages of logs to print.

**Comment by bmarolleau** [comment]
Good point - should not use the console and/or just in Node-RED verbose/debug mode. thx.

**Comment by bmarolleau** [comment]
Closed . pb solved commit 87e975a
