### ISSUE TITLE
Library List

### ISSUE THREAD

**Issue by waltercrombez** [IBM/node-red-contrib-db2-for-i#6]
Hi,
Running an injector with SQL statement with no qualified file name results in:
 
"Error or Warning while executing a DB statement: exec() SQLSTATE=42704 SQLCODE=-204 <file> in <library> type *FILE not found"

The user profile in the db2 node has the <library> defined in it's jobd's *LIBL. Shouldn't it use that *LIBL ?

**Comment by bmarolleau** [comment]
Hey! 
You're right.  
For now , we have to use qualified names with this Node and *LIBL in the user's JOBD is not used. 
I think this is the default idb behavior as we use SQL naming and not System naming with idb-connect. 
I'll give it a try on a next version, adding a Sys Naming optional mode and this line of code 
 connection.setConnAttr(idb.SQL_ATTR_DBC_SYS_NAMING, idb.SQL_TRUE); 
as mentioned by Aaron Bartell here : http://bit.ly/2xFtZHw
This tells the connection to use the *LIBL as specified by the user's *JOBD. 

Let me know if it is a problem for you, and I'll try to integrate this system naming mode soon.
Hope this helps.

**Comment by waltercrombez** [comment]
Hi,

Quick response, nice.

It is not a real problem, only cumbersome as I need to use different copies
of the same sql statement depending on the library where I want to be. So
the sooner, the better.

Tx

Walter

Op wo 10 jun. 2020 15:38 schreef bmarolleau <notifications@github.com>:
