### ISSUE TITLE
Not all files accessible

### ISSUE THREAD

**Issue by waltercrombez** [IBM/node-red-contrib-db2-for-i#7]
Hi,

Experimenting with node-red-contrib-db2-for-i I experienced a strange behaviour. For some files on the IBM i the result of a simple 'SELECT * FROM <file>' was nicely returned into the msg.payload, for others, the result was an empty msg.payload : string[0] . I could not figure out why. Any idea how to get this resolved ?

**Comment by bmarolleau** [comment]
Hi!  Can you share the kind of SQL query you are running, with a sample table DDL , to see if it is related to the node itself? As designed, the node should be able to run any SQL statement for select, update, delete. Assuming you have the necessary user (private/public) authority to access the data in Db2 for i.    Keep us posted, thx for the feedback.

**Comment by waltercrombez** [comment]
Hi,

I Attached a DSPFD and the SQL to create the file.
The SQL statement which I defined in a Function node is

<
msg.payload="select * from WCR_.DM0100p"; 
return msg;
<

[QPDSPFD_WALTERC_QPADEV000B_157363_19.pdf](https://github.com/IBM/node-red-contrib-db2-for-i/files/4824502/QPDSPFD_WALTERC_QPADEV000B_157363_19.pdf)

Tx VM

**Comment by waltercrombez** [comment]
[dm0100p.txt](https://github.com/IBM/node-red-contrib-db2-for-i/files/4824533/dm0100p.txt)

**Comment by bmarolleau** [comment]
Hi @waltercrombez 
Any news on this issue?  could you determine the cause of the issue , on your side?  
Keep us posted.
